{
  "response": [
    {
      "datetime": 1790967350,
      "device": "m51",
      "filename": "BananaOS_3.2.1_m51.zip",
      "id": "ab5ca2a8468a904363bc82563f7700b53b6321d445d9a5927381b5dfd09daf9a",
      "patch": "2026-08-05",
      "size": 5940232195,
      "urls": [
        "https://sourceforge.net/projects/bananaos/files/Samsung/3.2.x/full/BananaOS_3.2.1_m51.zip/download"
      ],
      "version": "3.2.1-1798c57",
      "incremental": 0
    },
    {
      "datetime": 1790967350,
      "device": "m51",
      "filename": "BananaOS_3.2.1_m51.zip",
      "id": "eb0c6f3122aad7c8fd35136dfec572c4d363dfd92f6d735bd00f404ebc3e2cb4",
      "patch": "2026-08-05",
      "size": 329580575,
      "urls": [
        "https://sourceforge.net/projects/bananaos/files/Samsung/3.2.x/incremental/BananaOS_3.2.1_m51-inc.zip/download"
      ],
      "version": "3.2.1-1798c57",
      "incremental": 1790967350
    }  ]
}
