name: 02 Mirror SourceForge to Pixeldrain 

on:
  workflow_dispatch:

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    timeout-minutes: 480

    strategy:
      fail-fast: false
      matrix:
        target: [a05s, a14, a52q, a52sxq, a53x, a71, a72q, a73xq, b0q, g0q, m51, m52xq, o1s, p3s, r0q, r8q, r9s, t2s]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Downloading BananaOS_3.2.1_${{ matrix.target }}.zip
        env:
          TARGET_CODENAME: ${{ matrix.target }}
        id: sf_download
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 480
          max_attempts: 3
          retry_on: error
          command: ./scripts/dl_full_zip.sh

      - name: Upload BananaOS_3.2.1_${{ matrix.target }}.zip to Pixeldrain
        env:
          PIXELDRAIN_API_KEY: ${{ secrets.PIXELDRAIN_API_KEY }}
        run: |
          curl -sL https://github.com/jkawamoto/go-pixeldrain/releases/download/v0.7.6/pd_0.7.6_linux_amd64.tar.gz | tar -xz pd
          for ROM in Samsung/*.zip ; do
            echo "Uploading $ROM to PixelDrain..."
            ./pd --api-key "$PIXELDRAIN_API_KEY" upload "$ROM" | sed 's|api/file|u|g'
          done
