name: Retry Galaxy A52s 5G (a52sxq)

on:
  workflow_run:
    workflows: ["Galaxy A52s 5G (a52sxq)"]
    types:
      - completed

permissions:
  actions: write

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Trigger Rerun
        env:
          GH_TOKEN: ${{ secrets.GH_JOJO_TOKEN }}
        run: |
          if [ "${{ github.event.workflow_run.run_attempt }}" -lt 3 ]; then
            gh run rerun ${{ github.event.workflow_run.id }} --failed
          else
            echo "Maximum retry attempts reached. Skipping."
          fi
